version: '3'
services:
  builder:
    privileged: true
    image: gitlab.ultramarine-linux.org:5050/release-engineering/koji-builder:latest
    volumes:
      - <path>:/opt/kojid.keytab,
      - <path>:/opt/kojid.conf
    environment:
      NFS_SERVER: <ip>,
      HOSTNAME: <hostname>
